import type { WorkspaceSnapshot, WikiDocument } from '@knoter/contracts';

export const localDate = (date = new Date()) =>
  `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const day = (offset: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return localDate(d);
};
const ago = (hours: number) => new Date(Date.now() - hours * 3600000).toISOString();

const documents: WikiDocument[] = [
  {
    id: 'rag',
    title: 'Retrieval-augmented generation',
    description: 'Connecting language models to knowledge they can actually reference.',
    category: 'AI & systems',
    icon: 'network',
    favorite: true,
    revision: 4,
    protected: false,
    sourceIds: ['paper-rag', 'note-retrieval', 'paper-attention'],
    relatedIds: ['embeddings', 'attention', 'knowledge'],
    updatedAt: ago(2),
    body: `## The idea\n\nA language model is a powerful reasoning interface, but its internal knowledge is a snapshot. **Retrieval-augmented generation (RAG)** connects that interface to a collection of documents at the moment a question is asked. [1](#source-paper-rag)\n\nInstead of relying entirely on what a model remembers, we give it relevant evidence and ask it to answer from that evidence. The result is a knowledge system that can evolve as its sources change.\n\n> The useful unit is not just an answer. It is an answer connected to the evidence that makes it trustworthy.\n\n## How the pieces fit together\n\nA practical retrieval pipeline has three distinct responsibilities:\n\n1. **Find the right context.** Search the knowledge base for passages that relate to the question.\n2. **Build an evidence set.** Combine useful passages, remove repetition, and keep their source references.\n3. **Generate a grounded answer.** Ask the model to explain what the evidence supports, with citations.\n\n[Keyword search](#/wiki/embeddings) catches exact names and phrases. [Embedding search](#/wiki/embeddings) finds passages that express a similar idea in different words. Combining the two makes retrieval more useful across research notes and papers. [2](#source-note-retrieval)\n\n## What makes a good knowledge base?\n\n| Principle | Why it matters |\n| --- | --- |\n| Focused documents | Each page answers one coherent topic |\n| Traceable claims | Readers can follow an idea back to its source |\n| Incremental updates | New evidence improves an existing page |\n| Human ownership | Manual edits survive the next background run |\n\n## Design notes for knoter\n\nThe [connected wiki](#/wiki/knowledge) is the primary retrieval layer. Original papers remain available as evidence, while the wiki provides an organized, connected account of what we have learned.\n\nA source update should trigger a review of dependent claims. It should not silently replace unrelated knowledge or undo a correction made by a person.\n\n## Open questions\n\n- How much context is enough before additional passages become noise?\n- When should two related pages be merged?\n- How should conflicting sources be represented in an answer?`,
  },
  {
    id: 'embeddings',
    title: 'Embeddings & semantic search',
    description: 'Finding the same idea, even when the words are different.',
    category: 'AI & systems',
    icon: 'brain',
    favorite: true,
    revision: 2,
    protected: false,
    sourceIds: ['note-retrieval'],
    relatedIds: ['rag', 'knowledge'],
    updatedAt: ago(5),
    body: `## Meaning as a vector\n\nAn embedding represents a piece of text as a list of numbers. Nearby vectors often correspond to texts with related meanings.\n\nThis lets a question about **remembering information** find a note about **knowledge retention**, even when the words do not match. [1](#source-note-retrieval)\n\n## Combining two kinds of search\n\nSemantic retrieval is useful for concepts. Keyword retrieval is useful for exact identifiers, names, and uncommon terms. A [retrieval-augmented system](#/wiki/rag) uses both.\n\n- Keep the embedding model and its dimensions with the index.\n- Rebuild derived vectors when the model changes.\n- Preserve the document revision associated with each chunk.\n\n> Similarity is a useful signal. It is not proof that a passage answers the question.\n\n## Chunking with context\n\nSplit a document along meaningful boundaries such as headings and paragraphs. A short passage should retain enough context to explain what its terms refer to.`,
  },
  {
    id: 'attention',
    title: 'Attention mechanisms',
    description: 'How a model decides which parts of its context matter.',
    category: 'AI & systems',
    icon: 'brain',
    favorite: false,
    revision: 3,
    protected: false,
    sourceIds: ['paper-attention'],
    relatedIds: ['rag', 'embeddings'],
    updatedAt: ago(25),
    body: `## Attention, intuitively\n\nAttention allows a model to combine information from different positions in a sequence. Each position can assign different weights to other positions based on the current context. [1](#source-paper-attention)\n\n## Queries, keys, and values\n\nA **query** expresses what a position is looking for. **Keys** describe what other positions offer. **Values** carry the information to combine.\n\nMultiple attention heads can represent different relationships at the same time.\n\n## Why this matters for retrieval\n\nRetrieved passages become part of a model's context. Their ordering, clarity, and relevance affect what information is available when producing an answer.\n\nAdding more context is therefore a design choice that should be evaluated on actual questions.`,
  },
  {
    id: 'knowledge',
    title: 'A garden of connected notes',
    description: 'A living knowledge base grows through small, thoughtful connections.',
    category: 'Research methods',
    icon: 'leaf',
    favorite: true,
    revision: 5,
    protected: true,
    sourceIds: ['note-garden'],
    relatedIds: ['rag', 'research'],
    updatedAt: ago(30),
    body: `## Grow ideas over time\n\nA useful note is a place to return to. It collects definitions, evidence, questions, and connections as understanding develops. [1](#source-note-garden)\n\n## Small notes, strong connections\n\nGive each page a clear purpose. Link related ideas when the relationship adds context. Use descriptive titles that make sense outside the original folder.\n\n- Write for your future self.\n- Keep evidence close to claims.\n- Revisit notes when new sources arrive.\n- Preserve uncertainty rather than smoothing it away.\n\n## Human and machine contributions\n\nAutomation can surface connections and propose updates. A person decides which interpretations are useful and which corrections should be preserved.\n\n> A knowledge base should remember how an idea changed, not only its latest wording.`,
  },
  {
    id: 'research',
    title: 'Reading a research paper',
    description: 'A repeatable process for turning papers into useful understanding.',
    category: 'Research methods',
    icon: 'flask',
    favorite: false,
    revision: 1,
    protected: false,
    sourceIds: ['note-reading'],
    relatedIds: ['knowledge', 'rag'],
    updatedAt: ago(48),
    body: `## Start with the question\n\nBefore reading every detail, identify the problem the authors are trying to solve and why it matters. [1](#source-note-reading)\n\n## Three passes\n\n1. **Orient.** Read the abstract, introduction, figures, and conclusion.\n2. **Understand.** Follow the method and the main evidence.\n3. **Evaluate.** Examine assumptions, limitations, and reproducibility.\n\n## Capture what changes your understanding\n\nRecord the contribution in your own words. Separate reported results from your interpretation. Save a precise reference for claims you want to reuse.\n\n## After reading\n\nConnect the paper to an existing concept page and list the questions that remain open.`,
  },
  {
    id: 'local-first',
    title: 'Local-first by design',
    description: 'Your workspace stays useful, with or without a connection.',
    category: 'Product thinking',
    icon: 'book',
    favorite: false,
    revision: 2,
    protected: false,
    sourceIds: ['note-local'],
    relatedIds: ['knowledge'],
    updatedAt: ago(52),
    body: `## Own the working copy\n\nA local-first workspace keeps a usable copy of its documents on the device. Reading and editing do not depend on a remote service being available. [1](#source-note-local)\n\n## Separate storage from inference\n\nLocal storage and local inference are different decisions. A workspace can keep files locally while using a configured model provider for selected operations.\n\n## Make recovery ordinary\n\nBackups, exports, and revision history are part of the everyday product. Derived search indexes should be rebuildable from saved documents.`,
  },
];

export function createSeed(): WorkspaceSnapshot {
  return {
    documents,
    sources: [
      {
        id: 'paper-rag',
        title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
        filename: 'retrieval-augmented-generation.pdf',
        type: 'pdf',
        size: 1240000,
        pages: 19,
        status: 'ready',
        addedAt: ago(3),
        documentIds: ['rag'],
        excerpt:
          'Demo source preview\n\nThis sample describes a retrieval system that combines a retriever with a language model. Relevant passages are supplied as context for generation.\n\nThis is illustrative demo content, not a verbatim extract from the original paper.',
      },
      {
        id: 'note-retrieval',
        title: 'Notes on hybrid retrieval',
        filename: 'hybrid-retrieval-notes.md',
        type: 'md',
        size: 4820,
        status: 'ready',
        addedAt: ago(6),
        documentIds: ['rag', 'embeddings'],
        excerpt:
          '# Notes on hybrid retrieval\n\nKeyword search preserves exact terms. Embedding search helps connect related ideas. A useful retrieval system combines the two and evaluates the resulting evidence.\n\nKeep the model version alongside every vector index.',
      },
      {
        id: 'paper-attention',
        title: 'Attention Is All You Need',
        filename: 'attention-is-all-you-need.pdf',
        type: 'pdf',
        size: 2210000,
        pages: 15,
        status: 'ready',
        addedAt: ago(26),
        documentIds: ['attention', 'rag'],
        excerpt:
          'Demo source preview\n\nAttention combines information from different sequence positions using context-dependent weights.\n\nThis is illustrative demo content. No PDF parsing or OCR has been performed.',
      },
      {
        id: 'note-garden',
        title: 'Growing a personal knowledge garden',
        filename: 'knowledge-garden.md',
        type: 'md',
        size: 3200,
        status: 'ready',
        addedAt: ago(32),
        documentIds: ['knowledge'],
        excerpt:
          '# A knowledge garden\n\nNotes are living documents. Keep them small enough to understand and connected enough to discover. Record your own corrections and preserve the source of an idea.',
      },
      {
        id: 'note-reading',
        title: 'A reading workflow',
        filename: 'reading-workflow.md',
        type: 'md',
        size: 2110,
        status: 'ready',
        addedAt: ago(48),
        documentIds: ['research'],
        excerpt:
          '# Read with a question\n\nOrient, understand, evaluate. Save the evidence that changes your understanding, and connect it to an existing note.',
      },
      {
        id: 'note-local',
        title: 'Offline workspace principles',
        filename: 'local-first.md',
        type: 'md',
        size: 1540,
        status: 'ready',
        addedAt: ago(54),
        documentIds: ['local-first'],
        excerpt:
          '# Local-first\n\nReading and editing should remain available offline. Backups and export are part of ownership.',
      },
    ],
    tasks: [
      {
        id: 't1',
        title: 'Compare keyword and semantic retrieval',
        done: false,
        dueDate: day(0),
        priority: 'high',
        documentId: 'rag',
      },
      {
        id: 't2',
        title: 'Add notes on chunking strategies',
        done: false,
        dueDate: day(0),
        priority: 'medium',
        documentId: 'embeddings',
      },
      {
        id: 't3',
        title: 'Read the attention paper again',
        done: false,
        dueDate: day(1),
        priority: 'medium',
        documentId: 'attention',
      },
      {
        id: 't4',
        title: 'Connect new notes to the knowledge garden',
        done: false,
        dueDate: day(2),
        priority: 'low',
        documentId: 'knowledge',
      },
      {
        id: 't5',
        title: 'Write a short research reading checklist',
        done: true,
        dueDate: day(-1),
        priority: 'low',
        documentId: 'research',
      },
      {
        id: 't6',
        title: 'Collect the first set of source papers',
        done: true,
        dueDate: day(-2),
        priority: 'medium',
      },
    ],
    events: [
      {
        id: 'e1',
        title: 'Weekly research review',
        date: day(0),
        time: '10:00',
        duration: 60,
        color: 'green',
        description: 'Review new sources and connect the ideas worth keeping.',
      },
      {
        id: 'e2',
        title: 'Deep reading · attention',
        date: day(1),
        time: '14:00',
        duration: 90,
        color: 'purple',
        description: 'A focused reading session with the attention paper.',
      },
      {
        id: 'e3',
        title: 'Knowledge garden check-in',
        date: day(3),
        time: '11:00',
        duration: 30,
        color: 'amber',
        description: 'Revisit open questions and tidy up related notes.',
      },
      {
        id: 'e4',
        title: 'Retrieval experiments',
        date: day(6),
        time: '09:30',
        duration: 120,
        color: 'green',
        description: 'Compare approaches using a small set of real questions.',
      },
    ],
    revisions: documents.map((d) => ({
      id: `rev-${d.id}`,
      documentId: d.id,
      revision: d.revision,
      title: d.title,
      body: d.body,
      createdAt: d.updatedAt,
      author: d.protected ? 'You' : 'knoter',
      summary: d.protected
        ? 'Refined the note and protected your edits'
        : 'Connected ideas from source material',
    })),
    activities: [
      {
        id: 'a1',
        title: 'Updated retrieval-augmented generation',
        detail: 'Connected 3 sources to one idea',
        createdAt: ago(2),
        kind: 'document',
        documentId: 'rag',
      },
      {
        id: 'a2',
        title: 'Added a new research source',
        detail: 'hybrid-retrieval-notes.md',
        createdAt: ago(6),
        kind: 'source',
      },
      {
        id: 'a3',
        title: 'Your knowledge garden is up to date',
        detail: 'Manual edits preserved',
        createdAt: ago(30),
        kind: 'document',
        documentId: 'knowledge',
      },
    ],
    messages: [],
    settings: { theme: 'light', workerPaused: false },
  };
}
